### ISSUE TITLE
Create a working ad-hoc coverage tool that at least measures coverage  of normal branches

### ISSUE THREAD

**Issue by lucianozapata** [lucianozapata/Python#12]
**Description**

Make a tool that we can use to measure coverage. This tool will guide us later and see if we can improve coverage!

**Comment by nikolim** [comment]
Created a seperate repo for that: 
https://github.com/nikolim/simple-coverage

**Comment by nikolim** [comment]
## simple-coverage (our own coverage tool)
![report1](https://user-images.githubusercontent.com/48829358/155320659-fca7a29a-003f-4b9f-a69f-735a75af6e73.png)
## coverage.py
![report2](https://user-images.githubusercontent.com/48829358/155320663-f4320779-ca3d-491a-a8fa-3c81d419207d.png)
