### ISSUE TITLE
Write 4 new Unit-tests to improve Coverage [Niko]

### ISSUE THREAD

**Issue by lucianozapata** [lucianozapata/Python#14]
**Description**

Write tests that improve coverage, as evidenced by the coverage tool. All tests have at least one meaningful assertion.

**Comment by nikolim** [comment]
Checkout last commit before adding the tests: 
`git checkout 7a9b3c7292cbd71fdc7723f449b9bbcbefbf9747`
Run the respective files 
`coverage run -m pytest searches/interpolation_search.py dynamic_programming/longest_sub_array.py sorts/quick_sort_3_partition.py dynamic_programming/integer_partition.py`
Create the coverage report 
`coverage report`

Checkout current (improved) branch: 
`git checkout issue\#14`
Run the respective files 
`coverage run -m pytest searches/interpolation_search.py dynamic_programming/longest_sub_array.py sorts/quick_sort_3_partition.py dynamic_programming/integer_partition.py`
Create the coverage report 
`coverage report`
